profiles:
  local:
    - docker-compose.yml
    - mount

  test:
    - docker-compose.yml
    - results

  prod:
    - docker-compose.yml
    - publish

tasks:
  jenkinslint:
    command: compose-flow compose run --rm app /bin/bash -c 'pylama -r results/pylama.log -f pylint || /bin/true'

  publish:
    command: compose-flow compose run --rm app /bin/bash ./scripts/publish.sh
